// front-end/src/app/modules/auth/components/login/login.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    ReactiveFormsModule
  ]
})
export class LoginComponent {
  loginForm: FormGroup;
  isLoading = false;
  hidePassword = true;
  errorMessage = '';

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    this.loginForm = this.fb.group({
      username: ['', Validators.required],
      password: ['', [Validators.required, Validators.minLength(6)]]
    });
  }

  getErrorMessage(controlName: string): string {
    const control = this.loginForm.get(controlName);
    if (!control?.errors || !control.touched) return '';

    if (control.hasError('required')) {
      return `${controlName.charAt(0).toUpperCase() + controlName.slice(1)} is required`;
    }
    if (control.hasError('minlength')) {
      return 'Password must be at least 6 characters';
    }
    return '';
  }

  onSubmit(): void {
    this.errorMessage = '';
    
    if (this.loginForm.valid) {
      this.isLoading = true;
      const { username, password } = this.loginForm.value;

      this.authService.login(username, password).subscribe({
        next: () => {
          this.router.navigate(['/dashboard']);
        },
        error: (error) => {
          this.isLoading = false;
          
          if (error.status === 401) {
            this.errorMessage = 'Invalid username or password';
          } else if (error.status === 404) {
            this.errorMessage = 'Account not found';
          } else if (!navigator.onLine) {
            this.errorMessage = 'Please check your internet connection';
          } else {
            this.errorMessage = 'Unable to connect to the server. Please try again later';
          }
        },
        complete: () => {
          this.isLoading = false;
        }
      });
    } else {
      Object.keys(this.loginForm.controls).forEach(key => {
        const control = this.loginForm.get(key);
        if (control?.invalid) {
          control.markAsTouched();
        }
      });
    }
  }
} 
<div class="login-container">
  <a class="back" href="home">
    <i class="fas fa-arrow-left"></i>
  </a>
  <div class="login-card">
    <!-- Header with Logo -->
    <div class="header">
      <div class="logo-section">
        <img src="assets/logo.png" alt="Nimbus Logo" class="logo">
        <h2>Nimbus</h2>
      </div>
      <div class="nav-links">
        <a href="home" class="active">Home</a>
        <a href="register">Join</a>
      </div>
    </div>

    <!-- Main Content -->
    <div class="signup-content">
      <h1>LOGIN TO NIMBUS</h1>
      <h2>Welcome Back <span>.</span></h2>
      <p class="login-link">Doesn't have an account? <a routerLink="/register">Sign up</a></p>

      <!-- Error Message -->
      <div class="error-message" *ngIf="errorMessage">
        <i class="fas fa-exclamation-circle"></i>
        <span>{{errorMessage}}</span>
      </div>

      <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="login-form">
        <div class="form-field">
          <label for="username">Username</label>
          <div class="input-wrapper">
            <input id="username"
                   type="text"
                   formControlName="username"
                   placeholder="Enter your username"
                   [class.error]="loginForm.get('username')?.invalid && loginForm.get('username')?.touched">
            <span class="error-message" *ngIf="getErrorMessage('username')">
              {{getErrorMessage('username')}}
            </span>
          </div>
        </div>

        <div class="form-field">
          <label for="password">Password</label>
          <div class="input-wrapper">
            <input id="password"
                   [type]="hidePassword ? 'password' : 'text'"
                   formControlName="password"
                   placeholder="Enter your password"
                   [class.error]="loginForm.get('password')?.invalid && loginForm.get('password')?.touched">
            <button type="button" 
                    class="toggle-password"
                    (click)="hidePassword = !hidePassword">
              <i [class]="hidePassword ? 'fas fa-eye-slash' : 'fas fa-eye'"></i>
            </button>
            <span class="error-message" *ngIf="getErrorMessage('password')">
              {{getErrorMessage('password')}}
            </span>
          </div>
        </div>
        <div class="form-options">
          <label class="remember-me">
            <input type="checkbox" >
            <span class="checkmark"></span>
            Remember me
          </label>
          <a href="#" class="forgot-password">Forgot password?</a>
        </div>
        <div class="action-buttons">
          <button type="reset" class="btn btn-secondary">
            Reset Form
          </button>
          <button type="submit" 
                  class="btn btn-primary"
                  [disabled]="loginForm.invalid || isLoading">
            <div class="spinner" *ngIf="isLoading"></div>
            <span *ngIf="!isLoading">Log In</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

// front-end/src/components/auth/login/Login.tsx
import './Login.css';
import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { FaArrowLeft, FaEye, FaEyeSlash, FaExclamationCircle } from 'react-icons/fa';
import { Link, useNavigate } from 'react-router-dom';
import { useAuthService } from '../../../contexts/ServiceContext';
import { ApiError } from '../../../core/models/ApiError';

type LoginFormData = {
    username: string;
    password: string;
};

const Login: React.FC = () => {
    const navigate = useNavigate();
    const authService = useAuthService();
    const [hidePassword, setHidePassword] = useState(true);
    const [errorMessage, setErrorMessage] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const { register, handleSubmit, formState: { errors, isValid } } = useForm<LoginFormData>({
        mode: 'onBlur',
        defaultValues: {
            username: '',
            password: ''
        }
    });

    const onSubmit = async (data: LoginFormData) => {
        setIsLoading(true);
        setErrorMessage(null);
        
        try {
            await authService.login(data.username, data.password);
            navigate('/dashboard');
        } catch (error) {
            if (error instanceof ApiError) {
                setErrorMessage(error.message);
                
                if (error.validationErrors) {
                    // Handle specific validation errors if needed
                    console.error('Validation errors:', error.validationErrors);
                }
            } else {
                setErrorMessage('An unexpected error occurred. Please try again.');
            }
        } finally {
            setIsLoading(false);
        }
    };

    const getErrorMessage = (field: keyof LoginFormData): string | undefined => {
        const errorObj = errors[field];
        if (!errorObj) return undefined;
        
        return errorObj.message;
    };

    return ( 
        <section id="login">
            <div className="login-container">
                <Link className="back" to="/">
                    <FaArrowLeft />
                </Link>
                <div className="login-card">
                    {/* Header with Logo */}
                    <div className="header">
                        <div className="logo-section">
                            <img src="/logo.png" alt="Nimbus Logo" className="logo" />
                            <h2>Nimbus</h2>
                        </div>
                        <div className="nav-links">
                            <Link to="/" className="active">Home</Link>
                            <Link to="/register">Join</Link>
                        </div>
                    </div>

                    {/* Main Content */}
                    <div className="signup-content">
                        <h1>LOGIN TO NIMBUS</h1>
                        <h2>Welcome Back <span>.</span></h2>
                        <p className="login-link">Doesn't have an account? <Link to="/register">Sign up</Link></p>

                        {/* Error Message */}
                        {errorMessage && (
                            <div className="error-message">
                                <FaExclamationCircle />
                                <span>{errorMessage}</span>
                            </div>
                        )}

                        <form onSubmit={handleSubmit(onSubmit)} className="login-form">
                            <div className="form-field">
                                <label htmlFor="username">Username</label>
                                <div className="input-wrapper">
                                    <input
                                        id="username"
                                        type="text"
                                        placeholder="Enter your username"
                                        className={errors.username ? 'error' : ''}
                                        {...register('username', {
                                            required: 'Username is required',
                                            minLength: {
                                                value: 3,
                                                message: 'Username must be at least 3 characters'
                                            }
                                        })}
                                    />
                                    {getErrorMessage('username') && (
                                        <span className="error-message">
                                            {getErrorMessage('username')}
                                        </span>
                                    )}
                                </div>
                            </div>

                            <div className="form-field">
                                <label htmlFor="password">Password</label>
                                <div className="input-wrapper">
                                    <input
                                        id="password"
                                        type={hidePassword ? 'password' : 'text'}
                                        placeholder="Enter your password"
                                        className={errors.password ? 'error' : ''}
                                        {...register('password', {
                                            required: 'Password is required',
                                            minLength: {
                                                value: 6,
                                                message: 'Password must be at least 6 characters'
                                            }
                                        })}
                                    />
                                    <button
                                        type="button"
                                        className="toggle-password"
                                        onClick={() => setHidePassword(!hidePassword)}
                                    >
                                        {hidePassword ? <FaEyeSlash /> : <FaEye />}
                                    </button>
                                    {getErrorMessage('password') && (
                                        <span className="error-message">
                                            {getErrorMessage('password')}
                                        </span>
                                    )}
                                </div>
                            </div>
                            <div className="form-options">
                                <label className="remember-me">
                                    <input type="checkbox" />
                                    <span className="checkmark"></span>
                                    Remember me
                                </label>
                                <a href="#" className="forgot-password">Forgot password?</a>
                            </div>
                            <div className="action-buttons">
                                <button type="reset" className="btn btn-secondary">
                                    Reset Form
                                </button>
                                <button
                                    type="submit"
                                    className="btn btn-primary"
                                    disabled={!isValid || isLoading}
                                >
                                    {isLoading ? (
                                        <div className="spinner"></div>
                                    ) : (
                                        <span>Log In</span>
                                    )}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    );
}
 
export default Login;
